#!/usr/bin/env node

"use strict";

const DEBUG = process.env.PRODUCTION != "1";
const EXTENSION_ID = DEBUG
    ? "mmcfiocbpgbfnboacbaddlofcackkikb"
    : "gaobldoddnlopccjidfbahcofidniohn";

const express = require("express");
const expressHandlebars = require("express-handlebars");

const app = express();

app.use(express.static("public"));
app.engine("handlebars", expressHandlebars());
app.set("view engine", "handlebars");

app.get("/", (req, res) => {
    res.redirect("https://chrome.google.com/webstore/detail/gaobldoddnlopccjidfbahcofidniohn");
    // res.render("landing");
});

app.get("/invite/:channel", (req, res) => {
    let destination = req.query.u;
    let parsed = new URL(destination);
    let siteName = parsed.hostname.replace(/^www\./, "") || "site";

    res.render("share", { siteName, EXTENSION_ID });
});

app.listen(3100);
